const DEFAULT_BALANCE_VALUE = 0;
const MIN_BALANCE_VALUE_PERMITTED = 0;
const DECIMAL_PLACES = 2;

export const MAGIC_NUMBERS = {
    DEFAULT_BALANCE_VALUE,
    MIN_BALANCE_VALUE_PERMITTED,
    DECIMAL_PLACES,
} as const;
